
import { Inter } from 'next/font/google'
import dynamic from 'next/dynamic';
import "../app/styles/global.scss";
// import ManagedDrawer from '@/app/components/common/drawer/managed-drawer';
// import ManagedDrawer from '@/app/components/common/drawer/managed-drawer';
import ManagedModal from '@/app/components/common/zoomModal/managed-zoomModal';
import Footer from './components/footer/Footer';
import Navbar from './components/navbar/Navbar';
import { ManagedUIContext } from '@/app/context/ui.context';

const ManagedDrawer = dynamic(
  () => import('@/app/components/common/drawer/managed-drawer'),
{ssr: false}
);


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ManagedUIContext>
          <Navbar />
          {children}
          <Footer />
          <ManagedModal />
          <ManagedDrawer />
        </ManagedUIContext>
      </body>
    </html>
  )
}
