import { Inter } from 'next/font/google'
import "../app/styles/global.scss";
import ManagedModal from './components/common/zoomModal/managed-zoomModal';
import Footer from './components/footer/Footer';
import Navbar from './components/navbar/Navbar';
import { ManagedUIContext } from './context/ui.context';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ManagedUIContext>
          <Navbar />
          {children}
          <Footer />
          <ManagedModal />
        </ManagedUIContext>
      </body>
    </html>
  )
}
